# dashboard/cids_data.py

CID_DICT = {
    # CID de Segurança (Para quando a planilha estiver vazia)
    "Z00": "Exame geral (Diagnóstico não informado)",

    # Lista Completa F00 - F99
    "F000": "Demência na doença de Alzheimer de início precoce",
    "F001": "Demência na doença de Alzheimer de início tardio",
    "F002": "Demência na doença de Alzheimer, forma atípica ou mista",
    "F009": "Demência não especificada na doença de Alzheimer",
    "F010": "Demência vascular de início agudo",
    "F011": "Demência por infartos múltiplos",
    "F012": "Demência vascular subcortical",
    "F013": "Demência vascular mista, cortical e subcortical",
    "F018": "Outra demência vascular",
    "F019": "Demência vascular não especificada",
    "F020": "Demência da doença de Pick",
    "F021": "Demência na doença de Creutzfeldt-Jakob",
    "F022": "Demência na doença de Huntington",
    "F023": "Demência na doença de Parkinson",
    "F024": "Demência na doença pelo vírus da imunodeficiência humana [HIV]",
    "F028": "Demência em outras doenças especificadas classificadas em outra parte",
    "F03": "Demência não especificada",
    "F04": "Síndrome amnésica orgânica não induzida pelo álcool ou por outras substâncias psicoativas",
    "F050": "Delirium não superposto a uma demência, assim descrito",
    "F051": "Delirium superposto a uma demência",
    "F058": "Outro delirium",
    "F059": "Delirium não especificado",
    "F060": "Alucinose orgânica",
    "F061": "Estado catatônico orgânico",
    "F062": "Transtorno delirante orgânico [tipo esquizofrênico]",
    "F063": "Transtornos do humor [afetivos] orgânicos",
    "F064": "Transtornos da ansiedade orgânicos",
    "F065": "Transtorno dissociativo orgânico",
    "F066": "Transtorno de labilidade emocional [astênico] orgânico",
    "F067": "Transtorno cognitivo leve",
    "F068": "Outros transtornos mentais especificados devidos a uma lesão e disfunção cerebral e a uma doença física",
    "F069": "Transtorno mental não especificado devido a uma lesão e disfunção cerebral e a uma doença física",
    "F070": "Transtorno orgânico da personalidade",
    "F071": "Síndrome pós-encefalítica",
    "F072": "Síndrome pós-traumática",
    "F078": "Outros transtornos orgânicos da personalidade e do comportamento devidos a doença cerebral, lesão e disfunção",
    "F079": "Transtorno orgânico não especificado da personalidade e do comportamento devido a doença cerebral, lesão e disfunção",
    "F09": "Transtorno mental orgânico ou sintomático não especificado",
    "F100": "Transtornos mentais e comportamentais devidos ao uso de álcool - intoxicação aguda",
    "F101": "Transtornos mentais e comportamentais devidos ao uso de álcool - uso nocivo para a saúde",
    "F102": "Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome de dependência",
    "F103": "Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome [estado] de abstinência",
    "F104": "Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome de abstinência com delirium",
    "F105": "Transtornos mentais e comportamentais devidos ao uso de álcool - transtorno psicótico",
    "F106": "Transtornos mentais e comportamentais devidos ao uso de álcool - síndrome amnésica",
    "F107": "Transtornos mentais e comportamentais devidos ao uso de álcool - transtorno psicótico residual ou de instalação tardia",
    "F108": "Transtornos mentais e comportamentais devidos ao uso de álcool - outros transtornos mentais ou comportamentais",
    "F109": "Transtornos mentais e comportamentais devidos ao uso de álcool - transtorno mental ou comportamental não especificado",
    "F110": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - intoxicação aguda",
    "F111": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - uso nocivo para a saúde",
    "F112": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome de dependência",
    "F113": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome [estado] de abstinência",
    "F114": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome de abstinência com delirium",
    "F115": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - transtorno psicótico",
    "F116": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - síndrome amnésica",
    "F117": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - transtorno psicótico residual ou de instalação tardia",
    "F118": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - outros transtornos mentais ou comportamentais",
    "F119": "Transtornos mentais e comportamentais devidos ao uso de opiáceos - transtorno mental ou comportamental não especificado",
    "F120": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - intoxicação aguda",
    "F121": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - uso nocivo para a saúde",
    "F122": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome de dependência",
    "F123": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome [estado] de abstinência",
    "F124": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome de abstinência com delirium",
    "F125": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - transtorno psicótico",
    "F126": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - síndrome amnésica",
    "F127": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - transtorno psicótico residual ou de instalação tardia",
    "F128": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - outros transtornos mentais ou comportamentais",
    "F129": "Transtornos mentais e comportamentais devidos ao uso de canabinóides - transtorno mental ou comportamental não especificado",
    "F130": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - intoxicação aguda",
    "F131": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - uso nocivo para a saúde",
    "F132": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome de dependência",
    "F133": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome [estado] de abstinência",
    "F134": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome de abstinência com delirium",
    "F135": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - transtorno psicótico",
    "F136": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - síndrome amnésica",
    "F137": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - transtorno psicótico residual ou de instalação tardia",
    "F138": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - outros transtornos mentais ou comportamentais",
    "F139": "Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos - transtorno mental ou comportamental não especificado",
    "F140": "Transtornos mentais e comportamentais devidos ao uso da cocaína - intoxicação aguda",
    "F141": "Transtornos mentais e comportamentais devidos ao uso da cocaína - uso nocivo para a saúde",
    "F142": "Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome de dependência",
    "F143": "Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome [estado] de abstinência",
    "F144": "Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome de abstinência com delirium",
    "F145": "Transtornos mentais e comportamentais devidos ao uso da cocaína - transtorno psicótico",
    "F146": "Transtornos mentais e comportamentais devidos ao uso da cocaína - síndrome amnésica",
    "F147": "Transtornos mentais e comportamentais devidos ao uso da cocaína - transtorno psicótico residual ou de instalação tardia",
    "F148": "Transtornos mentais e comportamentais devidos ao uso da cocaína - outros transtornos mentais ou comportamentais",
    "F149": "Transtornos mentais e comportamentais devidos ao uso da cocaína - transtorno mental ou comportamental não especificado",
    "F150": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - intoxicação aguda",
    "F151": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - uso nocivo para a saúde",
    "F152": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome de dependência",
    "F153": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome [estado] de abstinência",
    "F154": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome de abstinência com delirium",
    "F155": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - transtorno psicótico",
    "F156": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - síndrome amnésica",
    "F157": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - transtorno psicótico residual ou de instalação tardia",
    "F158": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - outros transtornos mentais ou comportamentais",
    "F159": "Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína - transtorno mental ou comportamental não especificado",
    "F160": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - intoxicação aguda",
    "F161": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - uso nocivo para a saúde",
    "F162": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome de dependência",
    "F163": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome [estado] de abstinência",
    "F164": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome de abstinência com delirium",
    "F165": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - transtorno psicótico",
    "F166": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - síndrome amnésica",
    "F167": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - transtorno psicótico residual ou de instalação tardia",
    "F168": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - outros transtornos mentais ou comportamentais",
    "F169": "Transtornos mentais e comportamentais devidos ao uso de alucinógenos - transtorno mental ou comportamental não especificado",
    "F170": "Transtornos mentais e comportamentais devidos ao uso de fumo - intoxicação aguda",
    "F171": "Transtornos mentais e comportamentais devidos ao uso de fumo - uso nocivo para a saúde",
    "F172": "Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome de dependência",
    "F173": "Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome [estado] de abstinência",
    "F174": "Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome de abstinência com delirium",
    "F175": "Transtornos mentais e comportamentais devidos ao uso de fumo - transtorno psicótico",
    "F176": "Transtornos mentais e comportamentais devidos ao uso de fumo - síndrome amnésica",
    "F177": "Transtornos mentais e comportamentais devidos ao uso de fumo - transtorno psicótico residual ou de instalação tardia",
    "F178": "Transtornos mentais e comportamentais devidos ao uso de fumo - outros transtornos mentais ou comportamentais",
    "F179": "Transtornos mentais e comportamentais devidos ao uso de fumo - transtorno mental ou comportamental não especificado",
    "F180": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - intoxicação aguda",
    "F181": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - uso nocivo para a saúde",
    "F182": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome de dependência",
    "F183": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome [estado] de abstinência",
    "F184": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome de abstinência com delirium",
    "F185": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - transtorno psicótico",
    "F186": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - síndrome amnésica",
    "F187": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - transtorno psicótico residual ou de instalação tardia",
    "F188": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - outros transtornos mentais ou comportamentais",
    "F189": "Transtornos mentais e comportamentais devidos ao uso de solventes voláteis - transtorno mental ou comportamental não especificado",
    "F190": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - intoxicação aguda",
    "F191": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - uso nocivo para a saúde",
    "F192": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome de dependência",
    "F193": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome [estado] de abstinência",
    "F194": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome de abstinência com delirium",
    "F195": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - transtorno psicótico",
    "F196": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - síndrome amnésica",
    "F197": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - transtorno psicótico residual ou de instalação tardia",
    "F198": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - outros transtornos mentais ou comportamentais",
    "F199": "Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas - transtorno mental ou comportamental não especificado",
    "F200": "Esquizofrenia paranóide",
    "F201": "Esquizofrenia hebefrênica",
    "F202": "Esquizofrenia catatônica",
    "F203": "Esquizofrenia indiferenciada",
    "F204": "Depressão pós-esquizofrênica",
    "F205": "Esquizofrenia residual",
    "F206": "Esquizofrenia simples",
    "F208": "Outras esquizofrenias",
    "F209": "Esquizofrenia não especificada",
    "F21": "Transtorno esquizotípico",
    "F220": "Transtorno delirante",
    "F228": "Outros transtornos delirantes persistentes",
    "F229": "Transtorno delirante persistente não especificado",
    "F230": "Transtorno psicótico agudo polimorfo, sem sintomas esquizofrênicos",
    "F231": "Transtorno psicótico agudo polimorfo, com sintomas esquizofrênicos",
    "F232": "Transtorno psicótico agudo de tipo esquizofrênico (schizophrenia-like)",
    "F233": "Outros transtornos psicóticos agudos, essencialmente delirantes",
    "F238": "Outros transtornos psicóticos agudos e transitórios",
    "F239": "Transtorno psicótico agudo e transitório não especificado",
    "F24": "Transtorno delirante induzido",
    "F250": "Transtorno esquizoafetivo do tipo maníaco",
    "F251": "Transtorno esquizoafetivo do tipo depressivo",
    "F252": "Transtorno esquizoafetivo do tipo misto",
    "F258": "Outros transtornos esquizoafetivos",
    "F259": "Transtorno esquizoafetivo não especificado",
    "F28": "Outros transtornos psicóticos não-orgânicos",
    "F29": "Psicose não-orgânica não especificada",
    "F300": "Hipomania",
    "F301": "Mania sem sintomas psicóticos",
    "F302": "Mania com sintomas psicóticos",
    "F308": "Outros episódios maníacos",
    "F309": "Episódio maníaco não especificado",
    "F310": "Transtorno afetivo bipolar, episódio atual hipomaníaco",
    "F311": "Transtorno afetivo bipolar, episódio atual maníaco sem sintomas psicóticos",
    "F312": "Transtorno afetivo bipolar, episódio atual maníaco com sintomas psicóticos",
    "F313": "Transtorno afetivo bipolar, episódio atual depressivo leve ou moderado",
    "F314": "Transtorno afetivo bipolar, episódio atual depressivo grave sem sintomas psicóticos",
    "F315": "Transtorno afetivo bipolar, episódio atual depressivo grave com sintomas psicóticos",
    "F316": "Transtorno afetivo bipolar, episódio atual misto",
    "F317": "Transtorno afetivo bipolar, atualmente em remissão",
    "F318": "Outros transtornos afetivos bipolares",
    "F319": "Transtorno afetivo bipolar não especificado",
    "F320": "Episódio depressivo leve",
    "F321": "Episódio depressivo moderado",
    "F322": "Episódio depressivo grave sem sintomas psicóticos",
    "F323": "Episódio depressivo grave com sintomas psicóticos",
    "F328": "Outros episódios depressivos",
    "F329": "Episódio depressivo não especificado",
    "F330": "Transtorno depressivo recorrente, episódio atual leve",
    "F331": "Transtorno depressivo recorrente, episódio atual moderado",
    "F332": "Transtorno depressivo recorrente, episódio atual grave sem sintomas psicóticos",
    "F333": "Transtorno depressivo recorrente, episódio atual grave com sintomas psicóticos",
    "F334": "Transtorno depressivo recorrente, atualmente em remissão",
    "F338": "Outros transtornos depressivos recorrentes",
    "F339": "Transtorno depressivo recorrente sem especificação",
    "F340": "Ciclotimia",
    "F341": "Distimia",
    "F348": "Outros transtornos do humor [afetivos] persistentes",
    "F349": "Transtorno do humor [afetivo] persistente não especificado",
    "F380": "Outros transtornos do humor [afetivos] isolados",
    "F381": "Outros transtornos do humor [afetivos] recorrentes",
    "F388": "Outros transtornos especificados do humor [afetivos]",
    "F39": "Transtorno do humor [afetivo] não especificado",
    "F400": "Agorafobia",
    "F401": "Fobias sociais",
    "F402": "Fobias específicas (isoladas)",
    "F408": "Outros transtornos fóbico-ansiosos",
    "F409": "Transtorno fóbico-ansioso não especificado",
    "F410": "Transtorno de pânico [ansiedade paroxística episódica]",
    "F411": "Ansiedade generalizada",
    "F412": "Transtorno misto ansioso e depressivo",
    "F413": "Outros transtornos ansiosos mistos",
    "F418": "Outros transtornos ansiosos especificados",
    "F419": "Transtorno ansioso não especificado",
    "F420": "Transtorno obsessivo-compulsivo com predominância de idéias ou de ruminações obsessivas",
    "F421": "Transtorno obsessivo-compulsivo com predominância de comportamentos compulsivos [rituais obsessivos]",
    "F422": "Transtorno obsessivo-compulsivo, forma mista, com idéias obsessivas e comportamentos compulsivos",
    "F428": "Outros transtornos obsessivo-compulsivos",
    "F429": "Transtorno obsessivo-compulsivo não especificado",
    "F430": "Reação aguda ao stress",
    "F431": "Estado de stress pós-traumático",
    "F432": "Transtornos de adaptação",
    "F438": "Outras reações ao stress grave",
    "F439": "Reação não especificada a um stress grave",
    "F440": "Amnésia dissociativa",
    "F441": "Fuga dissociativa",
    "F442": "Estupor dissociativo",
    "F443": "Estados de transe e de possessão",
    "F444": "Transtornos dissociativos do movimento",
    "F445": "Convulsões dissociativas",
    "F446": "Anestesia e perda sensorial dissociativas",
    "F447": "Transtorno dissociativo misto [de conversão]",
    "F448": "Outros transtornos dissociativos [de conversão]",
    "F449": "Transtorno dissociativo [de conversão] não especificado",
    "F450": "Transtorno de somatização",
    "F451": "Transtorno somatoforme indiferenciado",
    "F452": "Transtorno hipocondríaco",
    "F453": "Transtorno neurovegetativo somatoforme",
    "F454": "Transtorno doloroso somatoforme persistente",
    "F458": "Outros transtornos somatoformes",
    "F459": "Transtorno somatoforme não especificado",
    "F480": "Neurastenia",
    "F481": "Síndrome de despersonalização-desrealização",
    "F488": "Outros transtornos neuróticos especificados",
    "F489": "Transtorno neurótico não especificado",
    "F500": "Anorexia nervosa",
    "F501": "Anorexia nervosa atípica",
    "F502": "Bulimia nervosa",
    "F503": "Bulimia nervosa atípica",
    "F504": "Hiperfagia associada a outros distúrbios psicológicos",
    "F505": "Vômitos associados a outros distúrbios psicológicos",
    "F508": "Outros transtornos da alimentação",
    "F509": "Transtorno de alimentação não especificado",
    "F510": "Insônia não-orgânica",
    "F511": "Hipersonia não-orgânica",
    "F512": "Transtorno do ciclo vigília-sono devido a fatores não-orgânicos",
    "F513": "Sonambulismo",
    "F514": "Terrores noturnos",
    "F515": "Pesadelos",
    "F518": "Outros transtornos do sono devidos a fatores não-orgânicos",
    "F519": "Transtorno do sono devido a fatores não-orgânicos não especificados",
    "F520": "Ausência ou perda do desejo sexual",
    "F521": "Aversão sexual e ausência de prazer sexual",
    "F522": "Falha de resposta genital",
    "F523": "Disfunção orgásmica",
    "F524": "Ejaculação precoce",
    "F525": "Vaginismo não-orgânico",
    "F526": "Dispareunia não-orgânica",
    "F527": "Apetite sexual excessivo",
    "F528": "Outras disfunções sexuais não devidas a transtorno ou à doença orgânica",
    "F529": "Disfunção sexual não devida a transtorno ou à doença orgânica, não especificada",
    "F530": "Transtornos mentais e comportamentais leves associados ao puerpério não classificados em outra parte",
    "F531": "Transtornos mentais e comportamentais graves associados ao puerpério não classificados em outra parte",
    "F538": "Outros transtornos mentais e comportamentais associados ao puerpério não classificados em outra parte",
    "F539": "Transtorno mental e comportamental associado ao puerpério, não especificado",
    "F54": "Fatores psicológicos ou comportamentais associados a doença ou a transtornos classificados em outra parte",
    "F55": "Abuso de substâncias que não produzem dependência",
    "F59": "Síndromes comportamentais associados a transtornos das funções fisiológicas e a fatores físicos, não especificadas",
    "F600": "Personalidade paranóica",
    "F601": "Personalidade esquizóide",
    "F602": "Personalidade dissocial",
    "F603": "Transtorno de personalidade com instabilidade emocional",
    "F604": "Personalidade histriônica",
    "F605": "Personalidade anancástica",
    "F606": "Personalidade ansiosa [esquiva]",
    "F607": "Personalidade dependente",
    "F608": "Outros transtornos específicos da personalidade",
    "F609": "Transtorno não especificado da personalidade",
    "F61": "Transtornos mistos da personalidade e outros transtornos da personalidade",
    "F620": "Modificação duradoura da personalidade após uma experiência catastrófica",
    "F621": "Modificação duradoura da personalidade após doença psiquiátrica",
    "F628": "Outras modificações duradouras da personalidade",
    "F629": "Modificação duradoura da personalidade, não especificada",
    "F630": "Jogo patológico",
    "F631": "Piromania",
    "F632": "Roubo patológico [cleptomania]",
    "F633": "Tricotilomania",
    "F638": "Outros transtornos dos hábitos e dos impulsos",
    "F639": "Transtorno dos hábitos e impulsos, não especificado",
    "F640": "Transexualismo",
    "F641": "Travestismo bivalente",
    "F642": "Transtorno de identidade sexual na infância",
    "F648": "Outros transtornos da identidade sexual",
    "F649": "Transtorno não especificado da identidade sexual",
    "F650": "Fetichismo",
    "F651": "Travestismo fetichista",
    "F652": "Exibicionismo",
    "F653": "Voyeurismo",
    "F654": "Pedofilia",
    "F655": "Sadomasoquismo",
    "F656": "Transtornos múltiplos da preferência sexual",
    "F658": "Outros transtornos da preferência sexual",
    "F659": "Transtorno da preferência sexual, não especificado",
    "F660": "Transtorno da maturação sexual",
    "F661": "Orientação sexual egodistônica",
    "F662": "Transtorno do relacionamento sexual",
    "F668": "Outros transtornos do desenvolvimento psicossexual",
    "F669": "Transtorno do desenvolvimento sexual, não especificado",
    "F680": "Sintomas físicos aumentados por fatores psicológicos",
    "F681": "Produção deliberada ou simulação de sintomas ou de incapacidades, físicas ou psicológicas [transtorno fictício]",
    "F688": "Outros transtornos especificados da personalidade e do comportamento do adulto",
    "F69": "Transtorno da personalidade e do comportamento do adulto, não especificado",
    "F700": "Retardo mental leve - menção de ausência de ou de comprometimento mínimo do comportamento",
    "F701": "Retardo mental leve - comprometimento significativo do comportamento, requerendo vigilância ou tratamento",
    "F708": "Retardo mental leve - outros comprometimentos do comportamento",
    "F709": "Retardo mental leve - sem menção de comprometimento do comportamento",
    "F710": "Retardo mental moderado - menção de ausência de ou de comprometimento mínimo do comportamento",
    "F711": "Retardo mental moderado - comprometimento significativo do comportamento, requerendo vigilância ou tratamento",
    "F718": "Retardo mental moderado - outros comprometimentos do comportamento",
    "F719": "Retardo mental moderado - sem menção de comprometimento do comportamento",
    "F720": "Retardo mental grave - menção de ausência de ou de comprometimento mínimo do comportamento",
    "F721": "Retardo mental grave - comprometimento significativo do comportamento, requerendo vigilância ou tratamento",
    "F728": "Retardo mental grave - outros comprometimentos do comportamento",
    "F729": "Retardo mental grave - sem menção de comprometimento do comportamento",
    "F730": "Retardo mental profundo - menção de ausência de ou de comprometimento mínimo do comportamento",
    "F731": "Retardo mental profundo - comprometimento significativo do comportamento, requerendo vigilância ou tratamento",
    "F738": "Retardo mental profundo - outros comprometimentos do comportamento",
    "F739": "Retardo mental profundo - sem menção de comprometimento do comportamento",
    "F780": "Outro retardo mental - menção de ausência de ou de comprometimento mínimo do comportamento",
    "F781": "Outro retardo mental - comprometimento significativo do comportamento, requerendo vigilância ou tratamento",
    "F788": "Outro retardo mental - outros comprometimentos do comportamento",
    "F789": "Outro retardo mental - sem menção de comprometimento do comportamento",
    "F790": "Retardo mental não especificado - menção de ausência de ou de comprometimento mínimo do comportamento",
    "F791": "Retardo mental não especificado - comprometimento significativo do comportamento, requerendo vigilância ou tratamento",
    "F798": "Retardo mental não especificado - outros comprometimentos do comportamento",
    "F799": "Retardo mental não especificado - sem menção de comprometimento do comportamento",
    "F800": "Transtorno específico da articulação da fala",
    "F801": "Transtorno expressivo de linguagem",
    "F802": "Transtorno receptivo da linguagem",
    "F803": "Afasia adquirida com epilepsia [síndrome de landau-kleffner]",
    "F808": "Outros transtornos de desenvolvimento da fala ou da linguagem",
    "F809": "Transtorno não especificado do desenvolvimento da fala ou da linguagem",
    "F810": "Transtorno específico de leitura",
    "F811": "Transtorno específico da soletração",
    "F812": "Transtorno específico da habilidade em aritmética",
    "F813": "Transtorno misto de habilidades escolares",
    "F818": "Outros transtornos do desenvolvimento das habilidades escolares",
    "F819": "Transtorno não especificado do desenvolvimento das habilidades escolares",
    "F82": "Transtorno específico do desenvolvimento motor",
    "F83": "Transtornos específicos misto do desenvolvimento",
    "F840": "Autismo infantil",
    "F841": "Autismo atípico"
}