# Generated by Django 6.0.1 on 2026-01-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("cns", models.CharField(max_length=15, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("nome_mae", models.CharField(blank=True, max_length=255, null=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("sexo", models.CharField(blank=True, max_length=10, null=True)),
                ("raca_cor", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "municipio_codigo",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("endereco", models.TextField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("em_situacao_rua", models.BooleanField(default=False)),
                ("usuario_alcool_drogas", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Atendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "carater_atendimento",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "profissional_cns",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cbo", models.CharField(blank=True, max_length=10, null=True)),
                ("data", models.DateField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.paciente",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.procedimento",
                    ),
                ),
            ],
        ),
    ]
