# Generated by Django 6.0.1 on 2026-02-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_paciente_cep_paciente_latitude_paciente_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='cbo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='cid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
