# Generated by Django 6.0.1 on 2026-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_procedimento_cbo_procedimento_cid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="cns",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
